/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionId = IDL.Nat;
export const AnswerContent = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DisplayName = IDL.Text;
export const QuestionContent = IDL.Text;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Timestamp = IDL.Int;
export const Question = IDL.Record({
  'id' : QuestionId,
  'created' : Timestamp,
  'modified' : IDL.Opt(Timestamp),
  'content' : QuestionContent,
  'displayName' : IDL.Opt(DisplayName),
  'answer' : IDL.Opt(AnswerContent),
  'author' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'answerQuestion' : IDL.Func([QuestionId, AnswerContent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuestion' : IDL.Func(
      [IDL.Opt(DisplayName), QuestionContent],
      [QuestionId],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestions' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionId = IDL.Nat;
  const AnswerContent = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DisplayName = IDL.Text;
  const QuestionContent = IDL.Text;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Timestamp = IDL.Int;
  const Question = IDL.Record({
    'id' : QuestionId,
    'created' : Timestamp,
    'modified' : IDL.Opt(Timestamp),
    'content' : QuestionContent,
    'displayName' : IDL.Opt(DisplayName),
    'answer' : IDL.Opt(AnswerContent),
    'author' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'answerQuestion' : IDL.Func([QuestionId, AnswerContent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuestion' : IDL.Func(
        [IDL.Opt(DisplayName), QuestionContent],
        [QuestionId],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };