/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'content' : MessageContent,
  'displayName' : [] | [DisplayName],
  'author' : Principal,
  'timestamp' : Timestamp,
}
export type DisplayName = string;
export type MessageContent = string;
export type Timestamp = bigint;
export interface _SERVICE {
  'getMessages' : ActorMethod<[bigint, bigint], Array<ChatMessage>>,
  'sendMessage' : ActorMethod<[[] | [DisplayName], MessageContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];