/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageContent = IDL.Text;
export const DisplayName = IDL.Text;
export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : MessageContent,
  'displayName' : IDL.Opt(DisplayName),
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'getMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Opt(DisplayName), MessageContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageContent = IDL.Text;
  const DisplayName = IDL.Text;
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : MessageContent,
    'displayName' : IDL.Opt(DisplayName),
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'getMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Opt(DisplayName), MessageContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };